#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2MDEMO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbProducts")]
	public partial class dbProductsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
	#region Extensibility Method Definitions
	partial void OnCreated();
	#endregion
		
		public dbProductsDataContext() : 
				base(global::P2MDEMO.Properties.Settings.Default.dbProductsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbProductsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbProductsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbProductsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbProductsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_yfirflokkur> tbl_yfirflokkurs
		{
			get
			{
				return this.GetTable<tbl_yfirflokkur>();
			}
		}
		
		public System.Data.Linq.Table<tbl_undirflokkur> tbl_undirflokkurs
		{
			get
			{
				return this.GetTable<tbl_undirflokkur>();
			}
		}
		
		public System.Data.Linq.Table<tbl_vara> tbl_varas
		{
			get
			{
				return this.GetTable<tbl_vara>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_yfirflokkur")]
	public partial class tbl_yfirflokkur
	{
		
		private System.Nullable<int> _pk_yfirflokkur;
		
		private string _texti;
		
		public tbl_yfirflokkur()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_yfirflokkur", DbType="Float")]
		public System.Nullable<int> pk_yfirflokkur
		{
			get
			{
				return this._pk_yfirflokkur;
			}
			set
			{
				if ((this._pk_yfirflokkur != value))
				{
					this._pk_yfirflokkur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_texti", DbType="NVarChar(255)")]
		public string texti
		{
			get
			{
				return this._texti;
			}
			set
			{
				if ((this._texti != value))
				{
					this._texti = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_undirflokkur")]
	public partial class tbl_undirflokkur
	{
		
		private System.Nullable<int> _pk_undirflokkur;
		
		private System.Nullable<int> _fk_yfirflokkur;
		
		private string _texti;
		
		public tbl_undirflokkur()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_undirflokkur", DbType="Float")]
		public System.Nullable<int> pk_undirflokkur
		{
			get
			{
				return this._pk_undirflokkur;
			}
			set
			{
				if ((this._pk_undirflokkur != value))
				{
					this._pk_undirflokkur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_yfirflokkur", DbType="Float")]
		public System.Nullable<int> fk_yfirflokkur
		{
			get
			{
				return this._fk_yfirflokkur;
			}
			set
			{
				if ((this._fk_yfirflokkur != value))
				{
					this._fk_yfirflokkur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_texti", DbType="NVarChar(255)")]
		public string texti
		{
			get
			{
				return this._texti;
			}
			set
			{
				if ((this._texti != value))
				{
					this._texti = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_vara")]
	public partial class tbl_vara
	{
		
		private System.Nullable<int> _pk_vara;
		
		private System.Nullable<int> _fk_undiflokkur;
		
		private string _vorunumer_byrgja;
		
		private string _vara;
		
		private string _eining;
		
		private System.Nullable<double> _stk;
		
		public tbl_vara()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_vara", DbType="Float")]
		public System.Nullable<int> pk_vara
		{
			get
			{
				return this._pk_vara;
			}
			set
			{
				if ((this._pk_vara != value))
				{
					this._pk_vara = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_undiflokkur", DbType="Float")]
		public System.Nullable<int> fk_undiflokkur
		{
			get
			{
				return this._fk_undiflokkur;
			}
			set
			{
				if ((this._fk_undiflokkur != value))
				{
					this._fk_undiflokkur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vorunumer_byrgja", DbType="NVarChar(255)")]
		public string vorunumer_byrgja
		{
			get
			{
				return this._vorunumer_byrgja;
			}
			set
			{
				if ((this._vorunumer_byrgja != value))
				{
					this._vorunumer_byrgja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vara", DbType="NVarChar(255)")]
		public string vara
		{
			get
			{
				return this._vara;
			}
			set
			{
				if ((this._vara != value))
				{
					this._vara = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eining", DbType="NVarChar(255)")]
		public string eining
		{
			get
			{
				return this._eining;
			}
			set
			{
				if ((this._eining != value))
				{
					this._eining = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stk", DbType="Float")]
		public System.Nullable<double> stk
		{
			get
			{
				return this._stk;
			}
			set
			{
				if ((this._stk != value))
				{
					this._stk = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
